export const news_short = [
  {
    id: 0,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 1",
    postIntro: "A short post description of post 1",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 1,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 2",
    postIntro: "A short post description of post 2",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 2,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 3",
    postIntro: "A short post description of post 3",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 3,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 4",
    postIntro: "A short post description of post 4",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 4,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 5",
    postIntro: "A short post description of post 5",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 5,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 6",
    postIntro: "A short post description of post 6",
    postImg: "#",
    postImgAlt: "Alt",
  },
  {
    id: 6,
    postDate: "January 4, 2022",
    postTitle: "A Nice Post Title 7",
    postIntro: "A short post description of post 7",
    postImg: "#",
    postImgAlt: "Alt",
  },
];
